[workspace]
resolver = "3"
members = [
    "relay-server",
    "protocol",
    "backbone-lib",
    "games/dioxus-tic-tac-toe",
    "games/leptos-tic-tac-toe"
]


# For the server we will need opt-level='3'
[profile.release]
opt-level = 'z'       # Minimum space
lto = "fat"         # Aggressive Link Time Optimization
codegen-units = 1   

# Profile for profiling
[profile.profiling]
inherits = "release"
debug = true
