[package]
name = "leptos-tic-tac-toe"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos       = { version = "0.7", features = ["csr"] }
backbone-lib = { path = "../../backbone-lib" }
serde        = { version = "1.0", features = ["derive"] }
serde_json   = "1"
futures      = "0.3"
gloo-storage = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
gloo-net             = { version = "0.5", features = ["http"] }
web-sys              = { version = "0.3", features = ["RequestCredentials"] }
